# netlify.toml - Versión Final Corregida

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "api"
  external_node_modules = []

# Regla para la API (esta está bien)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

# REGLA CORREGIDA:
# Le decimos que solo aplique esta regla a las peticiones GET.
# Así, las peticiones POST del formulario no serán atrapadas aquí.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Method = ["GET"] } # <--- ESTA ES LA LÍNEA CLAVE