# netlify.toml - Versión Simplificada

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "api"

# Dejamos SOLO la regla para la API.
# Netlify es suficientemente inteligente para manejar la página de React y el formulario
# cuando el formulario tiene un "action" específico.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200