# Archivo de configuración para Netlify

[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

# Regla para que la API funcione
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

# Regla para que la página principal funcione
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200